[project]
name = "protac-permeability"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "huggingface-hub>=1.20.1",
    "matplotlib>=3.11.0",
    "numpy>=2.4.6",
    "optuna>=4.9.0",
    "pandas>=3.0.3",
    "py2opsin>=1.2.0",
    "rdkit>=2026.3.3",
    "scikit-learn>=1.9.0",
    "seaborn>=0.13.2",
]

[project.optional-dependencies]
mining = ["pmc-miner"]

[build-system]
requires = ["setuptools>=68", "wheel"]
build-backend = "setuptools.build_meta"

[tool.setuptools.packages.find]
include = ["protac_permeability*"]
exclude = ["extern*"]

[tool.uv.sources]
pmc-miner = { git = "https://github.com/yaochenr/PMC_Data_Mining" }
