[project]
name = "protac-permeability"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "numpy>=2.4.6",
    "pandas>=3.0.3",
    "pmc-miner",
    "py2opsin>=1.2.0",
]

[tool.uv.sources]
pmc-miner = { git = "https://github.com/yaochenr/PMC_Data_Mining" }
